import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const BASE='http://127.0.0.1:8291/index.html';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
let pass=0,fail=0;const F=[];const ok=(n,c)=>{if(c){pass++;console.log('  ✅',n);}else{fail++;F.push(n);console.log('  ❌',n);}};
async function device(email,name,pts){const ctx=await b.newContext({viewport:{width:430,height:920}});const p=await ctx.newPage();
  await p.goto(BASE); await p.waitForTimeout(300);
  await p.locator('#page-landing .btn').first().click();
  await p.click('#tab-register'); await p.fill('#reg-name',name);await p.fill('#reg-email',email);await p.fill('#reg-pw','pw1234');await p.fill('#reg-pw2','pw1234');
  await p.click('#form-register button[type=submit]'); await p.waitForTimeout(500);
  await p.check('#c1');await p.check('#c2');await p.check('#c3');await p.click('#consent-accept');await p.waitForTimeout(200);
  return p;}
console.log('\n🏫 Zero-Config gehostet — 2 Geräte, ein Ordner, kein DB-Setup');
const A=await device('anna@uni.de','Anna');
ok('A: Backend automatisch aktiv (relativ)', await A.evaluate(()=>window.MQ.Net.enabled()));
ok('A: Server-Konto (Server-ID)', /^[0-9a-f]{16}$/.test(await A.evaluate(()=>window.MQ.Auth.current().id)));
await A.evaluate(()=>window.MQ.Net.submit({name:'Anna',points:120,xp:240,coins:50,correctBets:6,challengesDone:4,streak:2,teamId:'green',ach:[]}));
const B=await device('ben@uni.de','Ben');
await B.evaluate(()=>window.MQ.Net.submit({name:'Ben',points:80,xp:180,coins:50,correctBets:9,challengesDone:3,streak:1,teamId:'blue',ach:[]}));
await B.waitForTimeout(200);
await A.click('.tabbar button[data-view=rank]'); await A.waitForTimeout(500);
const lb=await A.locator('#lb-card').innerText();
ok('A sieht geteiltes Leaderboard (Anna+Ben)', lb.includes('Anna')&&lb.includes('Ben'));
ok('A: Ben vor Anna (mehr richtige Wetten)', lb.indexOf('Ben')<lb.indexOf('Anna'));
await A.click('#seg-teams'); await A.waitForTimeout(500);
const t=await A.locator('#lb-card').innerText();
ok('A: Team-Battle live (Grün 120, Blau 80)', /120/.test(t)&&/80/.test(t)&&/Team Grün/.test(t)&&/Team Blau/.test(t));
console.log('\n===== ZERO-CONFIG-E2E: '+pass+' PASS / '+fail+' FAIL ====='); if(F.length)console.log(' - '+F.join('\n - '));
await b.close(); process.exit(fail?1:0);
